---
version: 2
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-5"
    checks:
      graphql/template-strings:
        enabled: false
  fixme:
    enabled: true
exclude_patterns:
- test/
- src/relay/__generated__/

